# Generated by Django 4.2.1 on 2023-10-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Переменная', 'verbose_name_plural': 'Переменные'},
        ),
        migrations.RemoveField(
            model_name='variable',
            name='id',
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Переменная'),
        ),
    ]
